# Generated by Django 5.1.2 on 2024-11-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
