# Generated by Django 5.1.2 on 2024-11-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0002_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
    ]
