# Generated by Django 5.1.2 on 2024-11-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0005_alter_resource_name_alter_resource_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task1',
        ),
    ]
