# Generated by Django 5.0.7 on 2024-11-12 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0008_resource_resource_type_alter_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity_used', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tasks/')),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.resource')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.supervisor')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcms.worker')),
            ],
        ),
        migrations.DeleteModel(
            name='Task2',
        ),
    ]
