# Generated by Django 5.0.7 on 2024-11-12 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0009_task_delete_task2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('blueprint', 'Blueprint'), ('contract', 'Contract'), ('inspection_report', 'Inspection Report')], max_length=20),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='appcms.manager')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='appcms.project')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='appcms.supervisor')),
            ],
        ),
    ]
